services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html
    networks:
      - main
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    expose:
      - '5000'
    networks:
      - main
    environment:
      - DB_TYPE=firebase
      - NODE_ENV=production
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - FIREBASE_CREDENTIAL=${FIREBASE_CREDENTIAL}
    restart: unless-stopped
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    networks:
      - main
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=https://aphori.st:5000

    depends_on:
      - backend

networks:
  main:
    driver: bridge