# Dockerfile for Express Back-End
FROM node:18-alpine

WORKDIR /app

# Install TypeScript globally in the container
RUN yarn global add typescript

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

COPY entrypoint_dev.sh /app/

# Make the entrypoint_dev script executable
RUN chmod +x /app/entrypoint_dev.sh
ENV NODE_ENV=dev

EXPOSE 5000

# Start the backend with the entrypoint_dev script
ENTRYPOINT ["/app/entrypoint_dev.sh"]
