# Dockerfile for Express Back-End
FROM node:18-alpine

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .

# Copy the entrypoint_dev script
COPY entrypoint_dev.sh /app/

# Make the entrypoint_dev script executable
RUN chmod +x /app/entrypoint_dev.sh

EXPOSE 5000

# Start the backend with the entrypoint_dev script
ENTRYPOINT ["/app/entrypoint_dev.sh"]
