# Parameter sweep configuration
parameter_sweeps:
  frequency_thresholds: [1000, 5000, 10000, 25000, 50000, 100000, 250000, 500000, 1000000, 2500000, 5000000, 10000000]
  similarity_thresholds: [0.3, 0.6, 0.8]
  puzzle_sizes: [4]
  algorithms: ["N=K", "N=K+D"]
  samples_per_configuration: 20

# Quality assessment metrics
quality_assessment:
  metrics:
    - "intracategory_word_distinctiveness"
    - "intercategory_discoherence"
    - "intracategory_coherence"
    - "difficulty_progression"
    - "generation_success_rate"
    - "generation_time"
    - "memory_usage"

# Performance targets
performance_targets:
  quality_score_improvement: 0.1
  success_rate_target: 0.95
  generation_time_reduction: 0.5
  category_coherence_target: 0.7

# Data collection settings
data_collection:
  batch_size: 10
  parallel_workers: 4
  timeout_seconds: 300

# Logging configuration
logging:
  level: "INFO"
  detailed_metrics: true
  performance_profiling: true
  quality_scoring: true

# NLP Pipeline Parameters
vocabulary:
  source: "nltk_words"
  frequency_threshold: 5000
  min_word_length: 2
  max_word_length: 15
  exclude_proper_nouns: true

categories:
  enabled_categories: ["person", "person_type", "location", "location_type", "organization", "organization_type", "event", "event_type", "product", "product_type", "creature", "skill", "category"]
  confidence_thresholds:
    person: 0.67
    person_type: 0.25
    location: 0.3
    location_type: 0.25
    organization: 0.3
    organization_type: 0.25
    event: 0.3
    event_type: 0.25
    product: 0.2
    product_type: 0.4
    creature: 0.61982528567314
    skill: 0.25
    category: 0.2
  embedding_thresholds:
    person: 0.62
    person_type: 0.15
    location: 0.3
    location_type: 0.15
    organization: 0.3
    organization_type: 0.15
    event: 0.3
    event_type: 0.15
    product: 0.1
    product_type: 0.3
    creature: 0.366375476121902
    skill: 0.15
    category: 0.1

scoring:
  dictionary_weight: 0.3
  embeddings_weight: 0.6
  llm_weight: 0.1
  min_confidence_threshold: 0.2
  multi_category_threshold: 0.5
  max_categories_per_word: 3

output:
  format: "json"
  include_metadata: true
  include_confidence_scores: true
  sort_by_confidence: true

processing:
  parallel_workers: 6
  batch_size: 1000
  timeout_seconds: 300

paths:
  input_vocab: "data/filtered_vocabulary.json"
  output_dir: "data/vocabs"
  temp_dir: "data/temp"

