stages:
  select_themes:
    cmd: python pipeline/theme_selector.py
    deps:
      - pipeline/theme_selector.py
      - ../data/categories/wiki_categories_filtered
    outs:
      - data/themes/selected_themes.json
    params:
      - puzzle_generation
      - themes
      - paths

  select_candidates:
    cmd: python pipeline/word_selector.py
    deps:
      - pipeline/word_selector.py
      - data/themes/selected_themes.json
      - ../../themes_index/themes_vectors.bin
      - ../../themes_index/themes_vocabulary.json
      - ../../themes_index/themes_metadata.json
    outs:
      - data/candidates/candidate_words.json
    params:
      - puzzle_generation
      - vector_search
      - paths

  enhance_with_gemini:
    cmd: python pipeline/gemini_enhancer.py
    deps:
      - pipeline/gemini_enhancer.py
      - data/themes/selected_themes.json
      - data/candidates/candidate_words.json
    outs:
      - data/cache/all_embeddings.csv:
          persist: true
      - data/embeddings/puzzle_embeddings.csv
      - data/outputs/final_puzzles.json
      - data/outputs/puzzle_metadata.json
      - reports/embedding_analysis.json
    params:
      - puzzle_generation
      - gemini
      - output
      - paths

  convert_to_firebase:
    cmd: node ../../../puzzle-generation/dist/use-gemini-output.js
    deps:
      - ../../../puzzle-generation/dist/use-gemini-output.js
      - ../../../puzzle-generation/dist/data-science-bridge.js
      - data/outputs/final_puzzles.json
    outs:
      - data/outputs/gemini-puzzles.json
      - data/outputs/gemini-puzzles_firebase.json

  copy_to_puzzle_generation:
    cmd: cp data/outputs/gemini-puzzles.json ../../../puzzle-generation/ && cp data/outputs/gemini-puzzles_firebase.json ../../../puzzle-generation/
    deps:
      - data/outputs/gemini-puzzles.json
      - data/outputs/gemini-puzzles_firebase.json