# Enhanced Wiki Puzzle Generation Pipeline with Gemini Embeddings

puzzle_generation:
  total_puzzle_count: 80  # Configurable puzzle count  
  words_per_theme: 4  # 4 words per theme for 4x4 puzzles
  themes_per_puzzle: 4  # 4 themes per puzzle
  candidate_words_per_theme: 50  # Initial vector search candidates
  min_similarity_threshold: 0.3
  theme_selection_method: "random"
  random_seed: 42  # For reproducible puzzle generation

themes:
  source: "../data/categories/wiki_categories_filtered"
  exclude_categories: 
    - "General reference"
    - "Research" 
    - "Academic disciplines"
    - "Library science"
  min_theme_length: 3  # Minimum characters for theme name

vector_search:
  data_source: "../../themes_index"
  use_lemmatized: true
  similarity_metric: "cosine"
  max_search_candidates: 50

gemini:
  model_id: "gemini-embedding-001"  # Updated to latest Gemini model
  embedding_dimension: 3072  # Full dimension as originally planned
  api_key_env: "GEMINI_API_KEY"
  task_type: "SEMANTIC_SIMILARITY"
  
  # Rate limiting configuration
  # Based on Gemini API limits: Free tier = 100 RPM, Tier 1 = 3000 RPM, Tier 2 = 5000 RPM, Tier 3 = 10000 RPM
  requests_per_minute: 2900  # Conservative limit for Tier 1 (2900 RPM to stay under 3000 RPM limit)
  min_request_interval: 0.1  # Minimum seconds between requests (0.1s = max 600 requests/second, but RPM limit applies)
  retry_base_delay: 1.0  # Base delay for exponential backoff on failures (1.0s)
  max_retries: 5  # Maximum retry attempts for failed requests

paths:
  themes: "data/themes/"
  candidates: "data/candidates/"
  embeddings: "data/embeddings/"
  outputs: "data/outputs/"
  reports: "reports/"
  cache: "data/cache/"

output:
  format: "json"
  include_metadata: true
  include_similarity_scores: true
  csv_precision: 6  # Decimal places for embedding values
  
  # Two CSV outputs
  embedding_cache_file: "data/cache/all_embeddings.csv"  # All generated embeddings
  puzzle_embeddings_file: "data/embeddings/puzzle_embeddings.csv"  # Final puzzle words only

logging:
  level: "INFO"
  detailed_output: true
  log_embedding_stats: true